FROM eclipse-temurin:17

LABEL mentainer="neetushaky7@gmail.com"

WORKDIR /app

COPY target/Organization-Service-0.0.1-SNAPSHOT.jar /app/OrganizationService

ENTRYPOINT ["java" ,"-jar","OrganizationService"]