FROM eclipse-temurin:17

LABEL mentainer="neetushaky7@gmail.com"

WORKDIR /app

COPY target/DepartmentService-0.0.1-SNAPSHOT.jar /app/DepartmentService

ENTRYPOINT ["java" ,"-jar" ,"DepartmentService"]